# Generated by Django 4.2.1 on 2023-05-15 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_endpoint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=4192)),
                ('give_point', models.DecimalField(decimal_places=1, max_digits=2)),
                ('Restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place', to='api_endpoint.restaurant')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ate', to='api_endpoint.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
