# Generated by Django 4.2.1 on 2023-05-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_endpoint', '0003_alter_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-05-15'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
