# Generated by Django 4.2.1 on 2023-05-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_endpoint', '0003_remove_food_restaurant_table_available_unavailable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
