# Generated by Django 4.2.1 on 2023-05-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_endpoint', '0004_alter_food_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='ave_point',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='no_of_people',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
