# Generated by Django 4.2.1 on 2023-05-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_endpoint', '0004_comment_created_at_comment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='no_of_comment',
            field=models.IntegerField(default=0),
        ),
    ]
