# Generated by Django 4.2.1 on 2023-05-13 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_endpoint', '0005_alter_food_ave_point_alter_order_no_of_people_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table', to='api_endpoint.table'),
        ),
    ]
