# Generated by Django 4.2.1 on 2023-05-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_endpoint', '0006_alter_order_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-05-13'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_food',
            field=models.ManyToManyField(blank=True, related_name='ordered_food', to='api_endpoint.orderfood'),
        ),
    ]
